spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/coworking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=n3u3da!

# MySQL datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Run schema.sql and data.sql on startup (creates tables + seeds if missing)
spring.sql.init.mode=always


#port
server.port: 8081
